version: 2

models:
  - name: report_uif
    description: "Reperte ante la UIF de jugadores sospechosos"
    # columns:
    #   - name: id
    #     description: "The primary key for this table"
    #     data_tests:
    #       - unique
    #       - not_null
